# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "OHBM BrainHack 2020"
email: ""
description: "OHBM Brainhack June 23-25th, 2020. Organized by the OHBM Open Science SIG."
baseurl: "/hackathon2020"
url: "https://ohbm.github.io/hackathon2020"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""

# Organizer Info
organizerName: "OHBM Open Science SIG"
organizerAlternateName: ""
organizerDescription: ""
organizerEmail: ""
organizerLogo: ""
organizerLink: ""

# Head
metaKeywords: "brainhack, montreal, neuroscience, AI"
twitterAccount: "@OhbmOpen"
socialImageSrcGooglePlus: ""
socialImageSrcTwitter: ""
socialImageSrcFacebook: ""

# Documents
c4pUrl: ""
c4sponsorsUrl: ""


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/#about/", text: "About"}
 #- {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/schedule", text: "Schedule"}
 - {permalink: "/logistics", text: "Logistics"}
 - {permalink: "/hackathon", text: "Hackathon"}
 - {permalink: "/team", text: "Team"}
 - {permalink: "/coc", text: "CoC"}
 - {permalink: "/sponsors", text: "Sponsors"}

bottomNavigationLinks:
 - {link: "https://www.youtube.com/watch?v=ZsCGEQzLSbQ", text: "Recordings of the unconference talks"}
rightNavigationButtons:
 - {link: "https://www.youtube.com/watch?v=ZsCGEQzLSbQ", text: "Recordings of the unconference talks"}

# Hero Block
heroImage: "mtl_photo.jpg"
heroTitle: "OHBM Brainhack <typeout>"
eventDate: "June 23-25th 2020"
typeoutTextValues: '"June 23-25th, 2020", "Montreal, QC", ""'
typeoutFallback: ""
heroButtons:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSc8l68UAClcdXHwl27UuUI5yHHBDuu-LtUulFTuNKRL70j_mw/viewform", text: "Help us design the TrainTrack!"}

# About Block
aboutTitle: "About OHBM BrainHack 2020"
aboutBlock:
 - {title: "Share Ideas", image: "undraw/undraw_share_link_qtxe.png", text: "Share your research and curiosity with other neuroimaging and computer science researchers."}
 - {title: "Build Projects", image: "undraw/undraw_code_typing_7jnv.png", text: "Try the presented tools on provided data or bring your own tools/data!" }
 - {title: "Be social", image: "undraw/undraw_Connecting_Teams_8ntu.png", text: "Get to meet and socialize with people from all over the world!"}
 - {title: "Learn Tools", image: "undraw/undraw_book_reading_kx9s.png", text: "Learn about brain imaging data and how to apply the latest computational tools to your data." }

# Guests block
# guestTitle: "Unconference talks"
# guestBlock:
#  - {title: "Riitta<br>Hari", image: "hari.jpg", text: "Prof. Em. Riitta Hari has pioneered the use of magnetoencephalography for studying sensory processing and motor control in healthy subjects and patient groups, with a main interest in the dynamics of human brain functions in naturalistic conditions. She will challenge our views during the unconference by sharing with us the unsolved questions of neuroscience."}

# Guests2 block
# guest2Title: "Ignite talks"
# guest2Block:
#  - {title: "Anna<br>Alexandrou", image: "alexandrou.jpg", text: ""}


# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Dept. of Neuroscience and Biomedical Engineering"
eventLocationLink: "http://nbe.aalto.fi/"
eventStreetAddress: "Rakentajanaukio 2"
eventAddressLocality: "Espoo"
eventAddressLocalityRegion: "Uusimaa"
eventPostalCode: "02150"
eventAddressCountry: "Finland"
eventStartTime: "2018-05-02T10:00"
eventDoorTime: "09:00"
eventEndTime: "2018-05-02T23:59"
eventPlaceCoordinates: "60.1877229, 24.8294535"
mapCenterCoordinates: "60.1877229, 24.8294535"
mapMobileCenterCoordinates: "60.1877229, 24.8294535"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Kinopalace Cinema"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "OHBMHackathon"
twitterFeed: "https://twitter.com/search?q=%23OHBMHackathon&src=typed_query"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Sponsors"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://twitter.com/ohbmopen", icon: "twitter"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://ossig.netlify.com/", text: "OHBM Open Science SIG"}
   - {link: "https://www.brainhack.org/", text: "Brainhack"}
 -
  title: "Organizers and contacts"
  links:
   - {link: "https://twitter.com/LevitisLiza", text: "Liza Levitis (Hackathon Co-chair)"}
   - {link: "https://twitter.com/RemiGau", text: "Remi Gau (Hackathon Co-chair)"}
   - {link: "mailto:ossig2019@inria.fr", text: "ossig2019@inria.fr."}
 -
  title: "FAQ"
  links:
   - {link: "/hackathon2020/coc", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "The OHBM Open Science SIG mission is to advance neuroimaging research by fostering the open sharing of ideas, data, and tools between members of the OHBM community. This will be accomplished by organizing educational events, supporting collaborative initiatives, and providing mentorship to junior researchers. In our first year, the SIG will focus on three contributions to the OHBM annual meeting: 1) organize a Hackathon to precede the annual meeting, 2) introduce the tools of open science by proposing a “Brainhacking 101” educational course, and 3) propose hands-on tutorials and collaborative Open Science projects during the OHBM conference."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Montreal"
directionDetailsCards:
 - {title: "From the Airport", information: 'The Pierre Elliot Trudeau (YUL) airport is about 30 minutes driving from the Old Port.'}
 - {title: "Public Transit", information: 'Google Transit is available in Montreal. Google maps is great for getting around, and the Transit app is handy for checking bus times if you choose to take public transportation. your way in Google Maps.'}
 - {title: "Lodging", information: 'For easy commuting to the Old Port, we recommend staying in an airbnb or hotel either in the Old Port, Griffintown, Downtown, or the Plateau.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Hackathon projects"
hackathonRows:
 - {title: "Automated Cortical Lesion Detection using Python Tools", image: "brain_lesion.png", details: "More information here <a href=\"https://github.com/barbrakr/CLF-python\">https://github.com/barbrakr/CLF-python</a>."}
 - {title: "Multi-table PCA methods for group and individual functional connectivity", image: "matrix.png", details: "C-MARINeR is a focused sub-project MARINeR: Multivariate Analysis and Resampling Inference for Neuroimaging in R. The C stands generally for connectivity, but specifically and statistically: covariance or correlation. The C-MARINeR project aims to develop and distribute an R package and ShinyApp. Together, R + Shiny allows for ease of use and, hopefully, simpler exploration of such complex data, and quicker adoption of the techniques. <br> More info here: <a href=https://github.com/jennyrieck/C-MARINeR>https://github.com/jennyrieck/C-MARINeR</a>."}
 - {title: "Bring your own method/data", image: "whatever.png", details: "The three methods suggested above are just a starting point. If a group of participants wants to work on something else, this is of course possible. We have also prepare some data to use the methods above, but if you have your own data, please bring it with you and try to hack it with the methods presented."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
